# file      : tests/basic/buildfile
# license   : Mozilla Public License 2.0; see accompanying LICENSE file

import libs = libca-certificates-curl%lib{ca-certificates-curl}

exe{driver}: {h c}{**} $libs testscript
