# file      : tests/basic/buildfile
# copyright : Copyright (c) 2009-2019 Code Synthesis Tools CC
# license   : Mozilla Public License 2.0; see accompanying LICENSE file

import libs = libca-certificates-curl%lib{ca-certificates-curl}

exe{driver}: {h c}{**} $libs testscript
